# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_bootrom.xci
# IP: The module: 'ila_bootrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_bootrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_bootrom.xci
# IP: The module: 'ila_bootrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/asus/Documents/ara-build-playground/cva6-stalone/cva6-stalone.srcs/sources_1/ip/ila_bootrom/ila_bootrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_bootrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
