# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.cache/wt [current_project]
set_property parent.project_path /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/typedef.svh
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/registers.svh
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/port.svh
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/assign.svh
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/assertions.svh
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/include/ara/ara.svh
}
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/typedef.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/typedef.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/registers.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/port.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/port.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/assign.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/include/axi/assign.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/assertions.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/include/common_cells/assertions.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/include/ara/ara.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/include/ara/ara.svh]
read_verilog -library xil_defaultlib -sv {
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/cva6/core/include/config_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/include/riscv_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/cva6/core/include/ariane_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/cva6/core/include/acc_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/include/rvv_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/common_cells/src/cf_math_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/axi/src/axi_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/include/ara_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/ara_dispatcher.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/ara_sequencer.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/counter.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/delta_counter.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/fall_through_register.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/fifo_v3.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/fixed_p_rounding.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_cast_multi.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_classifier.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_divsqrt_multi.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_divsqrt_th_32.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_fma.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_fma_multi.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_noncomp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_opgroup_block.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_opgroup_fmt_slice.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_opgroup_multifmt_slice.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_rounding.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_sdotp_multi.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_sdotp_multi_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/fpnew_top.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/lane.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/lane_sequencer.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpnew/src/lfsr_sr.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/lzc.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/masku/masku.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/operand_queue.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/operand_queues_stage.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/operand_requester.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/sldu/p2_stride_gen.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/popcount.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/power_gating_generic.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/rr_arb_tree.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/cva6/core/serdiv.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/simd_alu.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/simd_div.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/simd_mul.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/sldu/sldu.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/sldu/sldu_op_dp.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/spill_register.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/spill_register_flushable.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/stream_demux.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/stream_register.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/deps/common_cells/src/stream_xbar.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/tech_cells_generic/src/fpga/tc_clk_xilinx.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/valu.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/vector_fus_stage.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/vector_regfile.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/lane/vmfpu.sv
  /home/asus/Documents/ara-build-playground/ara-salone/ara-salone.srcs/sources_1/imports/ara-build-playground/src/ara.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ara -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ara.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ara_utilization_synth.rpt -pb ara_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
