# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/ariane.xdc

# XDC: imports/constraints/genesys-2.xdc

# IP: ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_master || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_master} -quiet] -quiet

# IP: ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_slave || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_slave} -quiet] -quiet

# IP: ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_mig_7_ddr3 || ORIG_REF_NAME==xlnx_mig_7_ddr3} -quiet] -quiet

# IP: ip/xlnx_clk_gen/xlnx_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_clk_gen || ORIG_REF_NAME==xlnx_clk_gen} -quiet] -quiet

# IP: ip/xlnx_axi_clock_converter/xlnx_axi_clock_converter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_clock_converter || ORIG_REF_NAME==xlnx_axi_clock_converter} -quiet] -quiet

# IP: ip/xlnx_axi_gpio/xlnx_axi_gpio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_gpio || ORIG_REF_NAME==xlnx_axi_gpio} -quiet] -quiet

# IP: ip/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter || ORIG_REF_NAME==xlnx_axi_dwidth_converter} -quiet] -quiet

# IP: ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_quad_spi || ORIG_REF_NAME==xlnx_axi_quad_spi} -quiet] -quiet
