# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.runs/synth_1/xilinx_ara_soc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.cache/wt [current_project]
set_property parent.project_path /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/apb/include
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/ara/include
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/axi/include
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/common_cells/include
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells/registers.svh
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include/hpdcache_typedef.svh
}
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells/registers.svh]
set_property is_global_include true [get_files /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include/hpdcache_typedef.svh]
read_verilog -library xil_defaultlib -sv {
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/config_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/include/riscv.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/riscv_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/ariane_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/acc_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/cf_math_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/acc_dispatcher.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/addr_decode.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/addr_decode_dync.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/include/rvv_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/include/ara_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/addrgen.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/alu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/amo_buffer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/apb/src/apb_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/apb_uart.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_dispatcher.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_sequencer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_soc.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_system.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ariane_regfile_ff.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ariane_regfile_fpga.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/axi_adapter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_atop_filter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_burst_splitter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_cut.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_demux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_demux_simple.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_converter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_downsizer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_upsizer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_err_slv.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_id_prepend.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_intf.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/axi_inval_filter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_lite_regs.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_lite_to_apb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_multicut.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_mux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/axi_shim.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_axi_lite.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_detailed_mem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_mem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_xbar.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/bht.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/branch_unit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/btb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/std_cache_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cache_ctrl.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/commit_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/compressed_decoder.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/controller.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/counter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/csr_buffer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/csr_regfile.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ctrl_registers.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/cvxif_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/cva6_accel_first_pass_decoder.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6_clic_controller.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_hpdcache_params_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_op_hpdcache_params_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/wt_cache_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_hpdcache_subsystem_axi_arbiter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_icache.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_mmu_sv32.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_mmu_sv39x4.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_ptw_sv32.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_ptw_sv39x4.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6_rvfi_probes.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_shared_tlb_sv32.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_tlb_sv32.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_tlb_sv39x4.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cvxif_fu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/decoder.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/delta_counter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ex_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/exp_backoff.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/fall_through_register.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/fifo_v3.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/fixed_p_rounding.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_cast_multi.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_classifier.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_divsqrt_multi.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_divsqrt_th_32.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_fma.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_fma_multi.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_noncomp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_block.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_fmt_slice.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_multifmt_slice.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_rounding.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_sdotp_multi.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_sdotp_multi_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_top.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/fpu_wrap.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/frontend.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memarray.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr_to_cache_set.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_plru.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/id_queue.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/id_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/instr_queue.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/instr_realign.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/instr_scan.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/issue_read_operands.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/issue_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/lane.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/lane_sequencer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lfsr.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lfsr_8bit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/lfsr_sr.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/load_store_unit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/load_unit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/lsu_bypass.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lzc.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/masku/masku.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/mem_to_banks_detailed.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/miss_handler.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/mmu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mult.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/multiplier.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/onehot_to_bin.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_queue.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_queues_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_requester.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/p2_stride_gen.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/perf_counters.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/src/pmp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/src/pmp_entry.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/popcount.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/power_gating_generic.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/ptw.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/ras.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/rr_arb_tree.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/scoreboard.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/serdiv.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/shift_reg.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/shift_reg_gated.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_alu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_div.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_mul.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/sldu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/sldu_op_dp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_clock_div.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_counter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_edge_detect.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_fifo.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_input_filter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_input_sync.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_mv_filter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/spill_register.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/spill_register_flushable.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/common/local/util/sram.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/std_cache_subsystem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/std_nbdcache.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/store_buffer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/store_unit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_arbiter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_arbiter_flushable.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_demux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fifo.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fork.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fork_dynamic.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_join.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_join_dynamic.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_mux.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_register.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_to_mem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_xbar.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/tag_cmp.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/tech_cells_generic/src/rtl/tc_clk.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/common/local/util/tc_sram_fpga_wrapper.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/tlb.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_baudgen.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_interrupt.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_receiver.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_transmitter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/unread.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/valu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vector_fus_stage.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vector_regfile.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vldu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vlsu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vmfpu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vstu.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_axi_adapter.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_cache_subsystem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_mem.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_missunit.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
  /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/xilinx_ara_soc.sv
}
read_ip -quiet /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/constrs_1/imports/Downloads/Genesys-2-Master.xdc
set_property used_in_implementation false [get_files /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/constrs_1/imports/Downloads/Genesys-2-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top xilinx_ara_soc -part xc7k325tffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_ara_soc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_ara_soc_utilization_synth.rpt -pb xilinx_ara_soc_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
