# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-552972-b670/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tffg900-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/apb/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/ara/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/axi/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/common_cells/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0
  } {
      /opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/apb/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/ara/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/axi/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/common_cells/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0
  } {
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells/registers.svh
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/config_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/include/riscv.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/riscv_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/ariane_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/acc_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/cf_math_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/acc_dispatcher.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/addr_decode.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/addr_decode_dync.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/include/rvv_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/include/ara_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/addrgen.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/alu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/amo_buffer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/apb/src/apb_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/apb_uart.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_dispatcher.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_sequencer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_soc.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ara_system.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ariane_regfile_ff.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ariane_regfile_fpga.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/axi_adapter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_atop_filter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_burst_splitter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_cut.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_demux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_demux_simple.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_converter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_downsizer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_dw_upsizer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_err_slv.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_id_prepend.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_intf.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/axi_inval_filter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_lite_regs.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_lite_to_apb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_multicut.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_mux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/axi_shim.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_axi_lite.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_detailed_mem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_to_mem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/axi/src/axi_xbar.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/bht.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/branch_unit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/btb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/std_cache_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cache_ctrl.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/commit_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/compressed_decoder.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/controller.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/counter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/csr_buffer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/csr_regfile.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/ctrl_registers.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/cvxif_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/cva6_accel_first_pass_decoder.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6_clic_controller.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_hpdcache_params_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_op_hpdcache_params_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/include/wt_cache_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_hpdcache_subsystem_axi_arbiter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_icache.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_mmu_sv32.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_mmu_sv39x4.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_ptw_sv32.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_ptw_sv39x4.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cva6_rvfi_probes.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_shared_tlb_sv32.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv32/cva6_tlb_sv32.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39x4/cva6_tlb_sv39x4.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cvxif_fu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/decoder.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/delta_counter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/ex_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/exp_backoff.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/fall_through_register.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/fifo_v3.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/fixed_p_rounding.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_cast_multi.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_classifier.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_divsqrt_multi.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_divsqrt_th_32.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_fma.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_fma_multi.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_noncomp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_block.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_fmt_slice.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_opgroup_multifmt_slice.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_rounding.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_sdotp_multi.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_sdotp_multi_wrapper.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpnew_top.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/fpu_wrap.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/frontend.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memarray.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr_to_cache_set.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_plru.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf_wrapper.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/id_queue.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/id_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/instr_queue.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/instr_realign.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/instr_scan.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/issue_read_operands.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/issue_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/lane.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/lane_sequencer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lfsr.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lfsr_8bit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/lfsr_sr.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/load_store_unit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/load_unit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/lsu_bypass.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/lzc.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/masku/masku.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/mem_to_banks_detailed.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/miss_handler.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/mmu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mult.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/multiplier.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/onehot_to_bin.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_queue.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_queues_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/operand_requester.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/p2_stride_gen.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/perf_counters.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/src/pmp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/pmp/src/pmp_entry.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/popcount.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/power_gating_generic.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/fpnew/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/ptw.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/frontend/ras.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/rr_arb_tree.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/scoreboard.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/serdiv.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/shift_reg.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/shift_reg_gated.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_alu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_div.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/simd_mul.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/sldu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/sldu/sldu_op_dp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_clock_div.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_counter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_edge_detect.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_fifo.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_input_filter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_input_sync.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/slib_mv_filter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/spill_register.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/spill_register_flushable.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/common/local/util/sram.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/std_cache_subsystem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/std_nbdcache.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/store_buffer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/store_unit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_arbiter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_arbiter_flushable.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_demux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fifo.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fork.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_fork_dynamic.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_join.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_join_dynamic.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_mux.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_register.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_to_mem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/stream_xbar.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/tag_cmp.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/tech_cells_generic/src/rtl/tc_clk.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/common/local/util/tc_sram_fpga_wrapper.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/mmu_sv39/tlb.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_baudgen.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_interrupt.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_receiver.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/apb_uart-master/src/uart_transmitter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/src/unread.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/valu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vector_fus_stage.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vector_regfile.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vldu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vlsu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/lane/vmfpu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/src/vlsu/vstu.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_axi_adapter.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_cache_subsystem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_mem.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_missunit.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
      /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/xilinx_ara_soc.sv
    }
      rt::read_verilog -include {
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/apb/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/ara/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/axi/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/includes/common_cells/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/common_cells/include/common_cells
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.srcs/sources_1/imports/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
    /home/asus/Documents/ara-build-playground/ara-soc/ara-soc_vsept1.gen/sources_1/ip/clk_wiz_0
  } ./.Xil/Vivado-552972-b670/realtime/clk_wiz_0_stub.v
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top xilinx_ara_soc
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-552972-b670/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
