name: Build ara on Ubuntu 22.04

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev device-tree-compiler libboost-regex-dev libboost-system-dev

      - name: Clone ara repository
        run: git clone https://github.com/pulp-platform/ara.git

      - name: Navigate to ara directory
        run: |
          cd ara
          ls -l

      - name: Update and sync submodules
        run: |
          git submodule update --init --recursive
          git submodule sync --recursive

      - name: Build Spike (riscv-isa-sim)
        run: |
          cd ara
          ls -la
          make riscv-isa-sim
