name: Build ara on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev device-tree-compiler libboost-regex-dev libboost-system-dev

      - name: Clone ara repository
        run: git clone https://github.com/pulp-platform/ara.git

      - name: Navigate to ara directory
        run: |
          cd ara
          ls -l

      - name: Install HW deps
        run: |
          cd ara/hardware
          ls -la
          make checkout
      - name: Make riscv toolchain
        run: |
          make riscv-isa-sim

      
